### ISSUE TITLE
求使用方法

### ISSUE THREAD

**Issue by yourxx** [srk24/clash-tproxy#1]
在 root 下，用 template-config.yaml 的内容替换掉我的 config.yaml .先运行 local-fake-ip-routing-mark-tproxy-iptables.sh 再运行 clash 回环了，是使用方法不对吗？

```
INFO[0000] DNS server listening at: [::]:1053
INFO[0000] Redirect proxy listening at: [::]:7892
INFO[0000] RESTful API listening at: [::]:9090
INFO[0000] TProxy server listening at: [::]:7893
INFO[0000] Mixed(http+socks) proxy listening at: [::]:7890
INFO[0001] [TCP] 192.168.1.2:47626 --> 111.99.115.26:9300 match GeoIP(CN) using DIRECT
INFO[0001] [TCP] 192.168.1.2:49844 --> 111.99.115.36:9395 match GeoIP(CN) using DIRECT
INFO[0001] [TCP] 192.168.1.2:45600 --> 111.99.115.26:9305 match GeoIP(CN) using DIRECT
INFO[0001] [TCP] 192.168.1.2:33948 --> 111.99.115.26:9310 match GeoIP(CN) using DIRECT
INFO[0001] [TCP] 192.168.1.2:51628 --> 111.99.115.26:9315 match GeoIP(CN) using DIRECT
INFO[0001] [TCP] 192.168.1.2:55426 --> 111.99.115.36:9320 match GeoIP(CN) using DIRECT
INFO[0001] [TCP] 192.168.1.2:60046 --> 111.99.115.36:9325 match GeoIP(CN) using DIRECT
INFO[0001] [TCP] 192.168.1.2:52468 --> 111.99.115.36:9330 match GeoIP(CN) using DIRECT
INFO[0001] [TCP] 192.168.1.2:37470 --> 111.99.115.36:9335 match GeoIP(CN) using DIRECT
INFO[0001] [TCP] 192.168.1.2:58894 --> 111.99.115.36:9340 match GeoIP(CN) using DIRECT
INFO[0001] [TCP] 192.168.1.2:45632 --> 111.99.115.26:9305 match GeoIP(CN) using DIRECT
```

**Comment by srk24** [comment]
能否贴一下你的脱敏配置，以及确定是否安装必须插件？  路由表是否有遗留干扰项？

**Comment by srk24** [comment]
`
# route rules
ip rule add fwmark 1 lookup 100
ip route add local 0.0.0.0/0 dev lo table 100

# init TP_CLASH
iptables -t mangle -N TP_CLASH
iptables -t mangle -F TP_CLASH

# local clients
iptables -t mangle -A TP_CLASH -d 0.0.0.0/8 -j RETURN
iptables -t mangle -A TP_CLASH -d 127.0.0.0/8 -j RETURN
iptables -t mangle -A TP_CLASH -d 10.0.0.0/8 -j RETURN
iptables -t mangle -A TP_CLASH -d 172.16.0.0/12 -j RETURN
iptables -t mangle -A TP_CLASH -d 192.168.0.0/16 -j RETURN
iptables -t mangle -A TP_CLASH -d 169.254.0.0/16 -j RETURN
iptables -t mangle -A TP_CLASH -d 224.0.0.0/4 -j RETURN
iptables -t mangle -A TP_CLASH -d 240.0.0.0/4 -j RETURN

# prevent dns redirect
iptables -t mangle -A TP_CLASH -p udp --dport 53 -j RETURN

# tproxy mark
iptables -t mangle -A TP_CLASH -p tcp -j TPROXY --on-port 7893 --tproxy-mark 1
iptables -t mangle -A TP_CLASH -p udp -j TPROXY --on-port 7893 --tproxy-mark 1

# redirect
iptables -t mangle -A PREROUTING -p tcp ! -m mark --mark 9 -j TP_CLASH
iptables -t mangle -A PREROUTING -p udp ! -m mark --mark 9 -j TP_CLASH

# init TP_CLASH_DNS
iptables -t nat -N TP_CLASH_DNS
iptables -t nat -F TP_CLASH_DNS

# redirect to clash dns
iptables -t nat -A TP_CLASH_DNS -p udp -j REDIRECT --to-ports 1053

# redirect
iptables -t nat -A PREROUTING -p udp --dport 53 ! -m mark --mark 9 -j TP_CLASH_DNS

# DNAT ICMP to local
iptables -t nat -A PREROUTING -d 198.18.0.0/16 -p icmp -j DNAT --to-destination 127.0.0.1


## host network 

# init TP_CLASH_LOCAL
iptables -t mangle -N TP_CLASH_LOCAL
iptables -t mangle -F TP_CLASH_LOCAL

# local clients
iptables -t mangle -A TP_CLASH_LOCAL -d 0.0.0.0/8 -j RETURN
iptables -t mangle -A TP_CLASH_LOCAL -d 127.0.0.0/8 -j RETURN
iptables -t mangle -A TP_CLASH_LOCAL -d 10.0.0.0/8 -j RETURN
iptables -t mangle -A TP_CLASH_LOCAL -d 172.16.0.0/12 -j RETURN
iptables -t mangle -A TP_CLASH_LOCAL -d 192.168.0.0/16 -j RETURN
iptables -t mangle -A TP_CLASH_LOCAL -d 169.254.0.0/16 -j RETURN
iptables -t mangle -A TP_CLASH_LOCAL -d 224.0.0.0/4 -j RETURN
iptables -t mangle -A TP_CLASH_LOCAL -d 240.0.0.0/4 -j RETURN

# prevent dns direct
iptables -t mangle -A TP_CLASH_LOCAL -p udp --dport 53 -j RETURN

# tproxy mark
iptables -t mangle -A TP_CLASH_LOCAL -p tcp -j MARK --set-xmark 1
iptables -t mangle -A TP_CLASH_LOCAL -p udp -j MARK --set-xmark 1

# redirect
iptables -t mangle -A OUTPUT -p tcp ! -m mark --mark 9 -j TP_CLASH_LOCAL
iptables -t mangle -A OUTPUT -p udp ! -m mark --mark 9 -j TP_CLASH_LOCAL

# init TP_CLASH_DNS
iptables -t nat -N TP_CLASH_DNS_LOCAL
iptables -t nat -F TP_CLASH_DNS_LOCAL

# redirect to clash dns
iptables -t nat -A TP_CLASH_DNS_LOCAL -p udp -j REDIRECT --to-ports 1053

# redirect
iptables -t nat -A OUTPUT -p udp --dport 53 ! -m mark --mark 9 -j TP_CLASH_DNS_LOCAL

# DNAT ICMP to local
iptables -t nat -A OUTPUT -d 198.18.0.0/16 -p icmp -j DNAT --to-destination 127.0.0.1
`

试试这个？

**Comment by srk24** [comment]
新版本已经发布，似乎修复了routing-mark的bug
